/* GENERATED by tools/build_pages.py — do not hand-edit.
   Carries this route's metadata, which page.tsx cannot because it is a client
   component. Copy lives in src/lib/seo.ts. */
import type { Metadata } from "next";
import { routeMetadata, RouteJsonLd } from "@/lib/route-meta";

export const metadata: Metadata = routeMetadata("/lead-detective");

export default function Layout({ children }: { children: React.ReactNode }) {
  return (<><RouteJsonLd path="/lead-detective" />{children}</>);
}
